base_url = "docsascode.codeandmedia.com"
compile_sass = true
title = "Docs title"
highlight_code = true
highlight_theme = "kronuz"
build_search_index = true

taxonomies = [
    {name = "tags", rss = true},
    {name = "authors", rss = true},
]
